config/routes.rb
Rails.application.routes.draw do
devise_for :users

  root to: "home#index"

  resources :users, only: [ :show, :edit, :update ] do 
    get :search, on: :collection   
  end

  resources :projects
  resources :investitors, only: :index
  resources :shortlists, only: [:index, :destroy] do
    post 'add_investitor/:investitor_id', action: :create, as: :add_investitor, on: :collection
  end



  get "testing_views/:folder/:view_to_load" => "testing_views#index"
#  get "users/update_states", as: "update_states"


  match "/states/:country_id" => "states#index", via: "get"
  match "/cities/:state_id" =>  "cities#index", via: "get"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :city
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  has_many :address
 

  def get_cities state_id
     @city = City.where(:state_id =>state_id)     
  end


end

app/models/country.rb
class Country < ApplicationRecord
  has_many :state
end

app/models/founder.rb
class Founder < User
  default_scope -> { with_profile("founder") }

  has_many :shortlists
end

app/models/investitor.rb
class Investitor < User
  default_scope -> { with_profile("investitor") }

  has_many :shortlists
  has_many :participations, class_name: "Participant"
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :investitor, class_name: "User"
  belongs_to :project, optional: true

  validates :amount_invested, presence: true
  validates :rating, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :founder, class_name: "User"

  has_many :participants, dependent: :destroy, autosave: true
  accepts_nested_attributes_for :participants, allow_destroy: true

  validates :name, presence: true
  validates :description, presence: true
end

app/models/shortlist.rb
class Shortlist < ApplicationRecord
  belongs_to :investitor, class_name: "User"
  belongs_to :founder, class_name: "User"

  validates :investitor_id, uniqueness: { scoped_to: :founder_id } 
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country
  has_many :city


 def get_states country_id
    @state =  State.where(:country => country_id) 
 end

end

app/models/user.rb
class User < ApplicationRecord
  extend Enumerize

  has_one :address
  accepts_nested_attributes_for :address


  # possible values: :confirmable, :lockable, :timeoutable, :recoverable, :trackable, :validatable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable

  has_many :shortlists, foreign_key: "founder_id"
  has_many :projects, foreign_key: "founder_id"

  serialize :profile, Array
  enumerize :profile, in: [ :investitor, :founder ], multiple: true

  scope :with_profile, ->(profile) { where("profile ~* ?", profile) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  respond_to :html, :json

  before_action :authenticate_user!

  def configure_devise_permitted_params
     devise_parameter_sanitizer.permit(:sign_up) do |user_params|
       user_params.permit(:email,
                          :name,
                          :profile,
                          :home_page,
                          :avatar
                         )
     end
   end


   def user_not_authorized
     flash[:error] = "You are not authorized to perform this action"
     redirect_to root_path
   end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index
    @cities = City.new
    @resul = @cities.get_cities params[:state_id]
    respond_with @resul
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/investitors_controller.rb
class InvestitorsController < ApplicationController

   def index
     authorize Investitor
     @investitor = Investitor.all

      respond_to do |format|
         format.html # index.html.erb
         format.json { render json: @investitor }
       end
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :load_projects, only: :index
  before_action :load_project, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user


  def index
  end


  def new
    build_project
    @project.participants.build
  end


  def create
    build_project
    save_project
  end


  def show
  end


  def edit
  end


  def update
    build_project
    save_project
  end


  def destroy
    destroy_project
  end


  private


  def destroy_project
    @project.destroy
    respond_with @project
  end


  def save_project
    respond_with @project if @project.save
  end


  def load_project
    @project = project_scope.find(params[:id])
  end


  def load_projects
    @projects = project_scope
  end


  def build_project
    @project ||= project_scope.build
    @project.attributes = project_params
  end


  def project_params
    return {} unless params[:project].present?
    params.require(:project).permit(:id, :name, :description,
                                    participants_attributes: [ :id, :_destroy, :investitor_id, :amount_invested, :rating ])
  end


  def project_scope
    policy_scope(Project).all
  end


  def authorize_user
    authorize Project
  end

end

app/controllers/shortlists_controller.rb
class ShortlistsController < ApplicationController
  before_action :load_shortlists, only: :index
  before_action :load_shortlist, only: :destroy
  before_action :authorize_user


  def index
  end


  def create
    build_shortlist
    save_shortlist
  end


  def destroy
    destroy_shortlist
  end


  private


  def destroy_shortlist
    @shortlist.destroy
    respond_with @shortlist
  end


  def save_shortlist
    respond_with(@shortlist, location: investitors_path ) if @shortlist.save!
  end


  def load_shortlist
    @shortlist = shortlist_scope.find(params[:id])
  end


  def load_shortlists
    @shortlists = shortlist_scope
  end


  def build_shortlist
    @shortlist = shortlist_scope.build
    @shortlist.investitor_id = params[:investitor_id]
  end


  def shortlist_scope
    policy_scope(Shortlist).all
  end


  def authorize_user
    authorize Shortlist
  end

end

app/controllers/states_controller.rb
class StatesController < ApplicationController
 

  def index
    @state = State.new
    @resul = @state.get_states params[:country_id]
    respond_with @resul
  end

end

app/controllers/testing_views_controller.rb
class TestingViewsController < ActionController::Base

  layout "application"

  def index
    render "#{params[:folder]}/#{params[:view_to_load]}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :load_user
  

  def index
  end

  def show 
  end
  

  def update
    build_user
    save_user
  end

  def search
    @search = User.with_profile("investitor")
    respond_with @search
  end

  private


  def save_user
    respond_with @user if @user.save
  end


  def build_user
    @user ||= user_scope.build
    @user.attributes = user_params
  end


  def user_params
    return {} unless params[:user].present?
    params.require(:user).permit(:email, :name, :description, :home_page,profile: [],
                                 address_attributes: [:street,:number,:district,:additional_information,:city_id] 
                                )
  end


  def load_user
    @user = user_scope.find(params[:id])
  end


  def user_scope
    User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shortlists_helper.rb
module ShortlistsHelper
  def add_to_shortlist_button(investitor)
    unless current_user.shortlists.where(investitor: investitor).any?
      link_to "Add to Shortlist", add_investitor_shortlists_path(investitor), method: :post
    end
  end
end

app/views/investitors/index.html.erb
<section class="container-fluid listing-investitor">
  <div class="wrapper">
    <div class="row">
      <div class="col-xs-12">

        <h2>Listing Investitor</h2>

        <ul class="listing-investitor-group">
          <% @investitor.each do |investitor| %>
          <li>
            <div class="investitor-avatar"></div>
            <div class="investitor-info">
              <h2><%= investitor.name %></h2>
              <p><%= investitor.email %></p>
              <p><%= investitor.description %></p>
            </div>
            <div class="investitor-btn">
              <%= add_to_shortlist_button(investitor) %>
            </div>
          </li>
          <% end %>
        </ul>


      </div>
    </div>
  </div>
</section>

app/views/projects/_form.html.erb
<%= simple_form_for @project do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>

  <%= button_tag "Add Participant", id: "add_participant", type: :button, data: { :"url-investitors" => investitors_path(format: :json) } %>

  <div id="participants">
    <%= f.simple_fields_for :participants, (@project.participants.present? ? @project.participants : @project.participants.build) do |pf| %>
      <div class="participant_fields">
        <%= pf.hidden_field :id %>
        <%= pf.hidden_field :_destroy, class: "destroy_field" %>
        <%= pf.input :investitor_id, collection: Investitor.all %>
        <%= pf.input :amount_invested, as: :string %>
        <%= pf.input :rating %>
      </div>
    <% end %>
  </div>

  <%= f.submit id: "submit_project" %>
<% end %>

app/views/projects/edit.html.erb
<section class="container-fluid projects">
  <div class="wrapper-small">
    <div class="row">
      <div class="col-xs-12">

        <h1>Edit Project</h1>

        <%= render "form" %>

      </div>
    </div>
  </div>
</section>

app/views/projects/index.html.erb
<section class="container-fluid projects">
  <div class="wrapper">
    <div class="row">
      <div class="col-xs-12">

        <h1>My Projects</h1>

        <%= link_to "New Project", new_project_path %>

        <ul class="projects-group">
          <% @projects.each do |project| %>
          <li>
            <div class="projects-avatar"></div>
            <div class="projects-info">
              <h2><%= project.name %></h2>
              <p><%= project.description %></p>
              <p><%= project.created_at %></p>
            </div>
            <div class="projects-btn">
              <%= link_to "Show", project %>
              <%= link_to "Edit", edit_project_path(project) %>
              <%= link_to "Delete", project, method: :delete %>
            </div>
          </li>
          <% end %>
        </ul>

      </div>
    </div>
  </div>
</section>

app/views/projects/new.html.erb
<section class="container-fluid projects">
  <div class="wrapper-small">
    <div class="row">
      <div class="col-xs-12">

        <h1>New Project</h1>

        <%= render "form" %>

      </div>
    </div>
  </div>
</section>

app/views/projects/show.html.erb
<section class="container-fluid projects">
  <div class="wrapper">
    <div class="row">
      <div class="col-xs-12">

        <h1>Show Project</h1>


        <ul class="projects-group">
          <li>
            <div class="projects-avatar"></div>
            <div class="projects-info">
              <h2><%= @project.name %></h2>
              <p><%= @project.description %></p>
            </div>
            <div class="projects-btn">
              <%= link_to "Edit", edit_project_path(@project) %>
            </div>
          </li>
        </ul>


      </div>
    </div>
  </div>
</section>

app/views/shortlists/index.html.erb
<section class="container-fluid shortlist">
  <div class="wrapper">
    <div class="row">
      <div class="col-xs-12">
        
        <h1>My Shortlist</h1>

        <ul class="listing-investitor-group">
          <% @shortlists.each do |shortlist| %>
          <li>
            <div class="investitor-avatar"></div>
            <div class="investitor-info">
              <h2><%= shortlist.investitor.name %></h2>
              <p><%= shortlist.investitor.email %></p>
              <p><%= shortlist.investitor.description %></p>
            </div>
            <div class="investitor-btn">
              <%= link_to "Remove from Shortlist", shortlist, method: :delete %>
            </div>
          </li>
          <% end %>
        </ul>

      </div>
    </div>
  </div>
</section>

app/views/users/_form.html.erb
        <%= simple_form_for @user do |f| %>
          <%= f.input :name %>
          <%= f.input :profile, as: :check_boxes %>
          <%= f.input :description, as: :text %>
          <%= f.input :home_page, as: :url %>
          <%= f.fields_for :address, @user.address.present? ? @user.address : @user.build_address do |af|%>
            <%= af.input :street %>
            <%= af.input :number %>
            <%= af.input :district %>
            <%= af.input :additional_information%>
          <% end %>


          <select id="countries" name="post[contry_id]">
               <% Country.all.each do |country| %>
               <option value="<%= country.id %>"><%= country.name %></option>
            <% end %>
           </select>


           <select id="states" name="post[state_id]">
             <option value="">select..</option>
           </select>


           <select id="cities" name="user[address_attributes][city_id]">
             <option value="">select..</option>
           </select>

          <%= f.submit %>

          <% end %>

app/views/users/edit.html.erb
<section class="container-fluid edit-profile">
  <div class="wrapper-small">
    <div class="row">
      <div class="col-xs-12">

        <h1>Edit Profile</h1>

        <%= render "form" %>

      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="container-fluid">
  <div class="wrapper">
    <div class="row">
      <div class="col-xs-12">

        <h1>Show user</h1>

        <p>
          <%= User.human_attribute_name(:name) %>: <%= @user.name %>
        </p>

        <p>
          <%= User.human_attribute_name(:email) %>: <%= @user.email %>
        </p>

        <p>
          <%= User.human_attribute_name(:profile) %>: <%= @user.profile.texts.join(", ") %>
        </p>

        <p>
          <%= User.human_attribute_name(:description) %>: <%= @user.description %>
        </p>

        <p>
          <%= User.human_attribute_name(:home_page) %>: <%= @user.home_page %>
        </p>

        <p>
          <%= link_to "Edit", edit_user_path(@user) %>
        </p>

      </div>
    </div>
  </div>
</section>