config/routes.rb
Rails.application.routes.draw do
devise_for :users

  root to: "home#index"

  resources :users, only: [ :show, :edit, :update ] do 
    get :search, on: :collection   
  end

  resources :projects
  resources :investitors, only: :index
  resources :shortlists, only: [:index, :destroy] do
    post 'add_investitor/:investitor_id', action: :create, as: :add_investitor, on: :collection
  end



  get "testing_views/:folder/:view_to_load" => "testing_views#index"
#  get "users/update_states", as: "update_states"


  match "/states/:country_id" => "states#index", via: "get"
  match "/cities/:state_id" =>  "cities#index", via: "get"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :city
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  has_many :address
 

  def get_cities state_id
     @city = City.where(:state_id =>state_id)     
  end


end

app/models/country.rb
class Country < ApplicationRecord
  has_many :state
end

app/models/founder.rb
class Founder < User
  default_scope -> { with_profile("founder") }

  has_many :shortlists
end

app/models/investitor.rb
class Investitor < User
  default_scope -> { with_profile("investitor") }

  has_many :shortlists
  has_many :participations, class_name: "Participant"
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :investitor, class_name: "User"
  belongs_to :project, optional: true

  validates :amount_invested, presence: true
  validates :rating, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :founder, class_name: "User"

  has_many :participants, dependent: :destroy, autosave: true
  accepts_nested_attributes_for :participants, allow_destroy: true

  validates :name, presence: true
  validates :description, presence: true
end

app/models/shortlist.rb
class Shortlist < ApplicationRecord
  belongs_to :investitor, class_name: "User"
  belongs_to :founder, class_name: "User"

  validates :investitor_id, uniqueness: { scoped_to: :founder_id } 
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country
  has_many :city


 def get_states country_id
    @state =  State.where(:country => country_id) 
 end

end

app/models/user.rb
class User < ApplicationRecord
  extend Enumerize

  has_one :address
  accepts_nested_attributes_for :address


  # possible values: :confirmable, :lockable, :timeoutable, :recoverable, :trackable, :validatable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable

  has_many :shortlists, foreign_key: "founder_id"
  has_many :projects, foreign_key: "founder_id"

  serialize :profile, Array
  enumerize :profile, in: [ :investitor, :founder ], multiple: true

  scope :with_profile, ->(profile) { where("profile ~* ?", profile) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  respond_to :html, :json

  before_action :authenticate_user!

  def configure_devise_permitted_params
     devise_parameter_sanitizer.permit(:sign_up) do |user_params|
       user_params.permit(:email,
                          :name,
                          :profile,
                          :home_page,
                          :avatar
                         )
     end
   end


   def user_not_authorized
     flash[:error] = "You are not authorized to perform this action"
     redirect_to root_path
   end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index
    @cities = City.new
    @resul = @cities.get_cities params[:state_id]
    respond_with @resul
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :load_projects, only: :index
  before_action :load_project, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user


  def index
  end


  def new
    build_project
    @project.participants.build
  end


  def create
    build_project
    save_project
  end


  def show
  end


  def edit
  end


  def update
    build_project
    save_project
  end


  def destroy
    destroy_project
  end


  private


  def destroy_project
    @project.destroy
    respond_with @project
  end


  def save_project
    respond_with @project if @project.save
  end


  def load_project
    @project = project_scope.find(params[:id])
  end


  def load_projects
    @projects = project_scope
  end


  def build_project
    @project ||= project_scope.build
    @project.attributes = project_params
  end


  def project_params
    return {} unless params[:project].present?
    params.require(:project).permit(:id, :name, :description,
                                    participants_attributes: [ :id, :_destroy, :investitor_id, :amount_invested, :rating ])
  end


  def project_scope
    policy_scope(Project).all
  end


  def authorize_user
    authorize Project
  end

end

app/controllers/shortlists_controller.rb
class ShortlistsController < ApplicationController
  before_action :load_shortlists, only: :index
  before_action :load_shortlist, only: :destroy
  before_action :authorize_user


  def index
  end


  def create
    build_shortlist
    save_shortlist
  end


  def destroy
    destroy_shortlist
  end


  private


  def destroy_shortlist
    @shortlist.destroy
    respond_with @shortlist
  end


  def save_shortlist
    respond_with(@shortlist, location: investitors_path ) if @shortlist.save!
  end


  def load_shortlist
    @shortlist = shortlist_scope.find(params[:id])
  end


  def load_shortlists
    @shortlists = shortlist_scope
  end


  def build_shortlist
    @shortlist = shortlist_scope.build
    @shortlist.investitor_id = params[:investitor_id]
  end


  def shortlist_scope
    policy_scope(Shortlist).all
  end


  def authorize_user
    authorize Shortlist
  end

end

app/controllers/states_controller.rb
class StatesController < ApplicationController
 

  def index
    @state = State.new
    @resul = @state.get_states params[:country_id]
    respond_with @resul
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :load_user
  

  def index
  end

  def show 
  end
  

  def update
    build_user
    save_user
  end

  def search
    @search = User.with_profile("investitor")
    respond_with @search
  end

  private


  def save_user
    respond_with @user if @user.save
  end


  def build_user
    @user ||= user_scope.build
    @user.attributes = user_params
  end


  def user_params
    return {} unless params[:user].present?
    params.require(:user).permit(:email, :name, :description, :home_page,profile: [],
                                 address_attributes: [:street,:number,:district,:additional_information,:city_id] 
                                )
  end


  def load_user
    @user = user_scope.find(params[:id])
  end


  def user_scope
    User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shortlists_helper.rb
module ShortlistsHelper
  def add_to_shortlist_button(investitor)
    unless current_user.shortlists.where(investitor: investitor).any?
      link_to "Add to Shortlist", add_investitor_shortlists_path(investitor), method: :post
    end
  end
end

app/views/layouts/_banner.html.erb
<div class="margin-header"></div>
<div class="container-fluid banner-home">
  <div>
    <h1>Raise money on your terms.</h1>
    <p>Search for investors and read reviewa from founders about their investors</p>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="wrapper">
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="wrapper header-flex">
    <div class="header-logo"> <%= image_tag "svg/magnifying-glass.svg" %> <h3>Glassdollar</h3></div>
    <form class="header-search" action="index.html" method="post">
      <input type="text" name="search" placeholder="Search Investors">
      <button type="button" name="button" >Search</button>
    </form>
    <div>
      <%= link_to "My Profile", edit_user_path(current_user) %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    </div>
  </nav>

  <% if current_user.profile.founder? %>

    <div class="header-menu">
      <ul>
        <li><%= link_to "Investitors", investitors_path %></li>
        <li><%= link_to "Projects", projects_path %></li>
        <li><%= link_to "Shortlist", shortlists_path %></li>
      </ul>
    </div>

  <% end %>

</header>

app/views/layouts/_quick-search.html.erb
<section class="quick-search">
  <div class="wrapper-quick-search">
    <h2>Quick Search</h2>

    <ul>
      <li>
        <a href="#">Best</a>
      </li>
      <li>
        <a href="#">Trending</a>
      </li>
      <li>
        <a href="#">Trust in founder decisions</a>
      </li>
      <li>
        <a href="#">Seed</a>
      </li>
      <li>
        <a href="#">Angels</a>
      </li>
    </ul>

  </div>
</section>

app/views/layouts/_select-areas.html.erb
<section class="select-areas">
  <div class="wrapper">
    <h2>Select Areas</h2>
    <div class="areas">
      <div>
        <div></div>
        <p>Berlin</p>
      </div>

      <div>
        <div></div>
        <p>Berlin</p>
      </div>

      <div>
        <div></div>
        <p>Berlin</p>
      </div>

      <div>
        <div></div>
        <p>Berlin</p>
      </div>

      <div>
        <div></div>
        <p>Berlin</p>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_select-industries.html.erb
<section class="select-industries">
  <div class="wrapper">
    <h2>Select Industries</h2>
    <div class="industries">
      <div>
        <div></div>
        <p>Adtech</p>
      </div>

      <div>
        <div></div>
        <p>Adtech</p>
      </div>

      <div>
        <div></div>
        <p>Adtech</p>
      </div>

      <div>
        <div></div>
        <p>Adtech</p>
      </div>

      <div>
        <div></div>
        <p>Adtech</p>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_tag-search.html.erb
<section class="search-tag">


</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GlassDollar</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/banner' %>
    <%= yield %>
    <%= render 'layouts/tag-search' %>
    <%= render 'layouts/quick-search' %>
    <%= render 'layouts/select-areas' %>
    <%= render 'layouts/select-industries' %>
    <%= render 'layouts/footer' %>
  </body>
</html>